### ISSUE TITLE
Btrfs failed to restore broken plasma

### ISSUE THREAD

**Issue by ShalokShalom** [garuda-linux/btrfs-assistant#1]
Hi there :)

I just tried your OS the first time, and was might impressed by the design, preinstalled software and overall integration of different tools into one coherent system.

As most systems, you fail to provide support for my rtl88x2bu and I had to pacman -U it, bc and dkms from the Chaotic repos via my phone.

This is already something, most users won't do, so you leave a lot of customers on the line by failing to provide support out of the box.

After I installed the driver, it seemed like its working, but then the system hang up itself, as I tried to read 'lsusb'

Upon restart from this freeze, I found myself without panel and dock.

I tried to find the config file, but found only .kde4 in the home folder.

Nonetheless, I restored the backup, that the system had from thr installation of the Wifi driver and, sure enough, this couldnt fix the issue.

Now, so as I understand btrfs and snapshots, this should be virtually impossible, since as the snapshot was taken, the system was still in good shape. 

I also looked into the guest account, and that one had always kept the panel and dock, it didnt loose them.

So, risking this becoming a lengthy review: I really like Geruda, but its that unreliable, that I couldnt even finish the initial system configuration, despite 7 years of deeper Linux knowledge.

I used the Geruda KDE Gamer edition.
I could provide logs, in case you are interested.

Waiting for an ISO that provides support for that chip out of the box.

P.S: That one is advertised as Linux compatible, by the way.

**Comment by JustTNE** [comment]
I don't know how this is relevant to btrfs-assistant tbh. I am rather perplexed.
